### ISSUE TITLE
Create resources directory and place one test resource there

### ISSUE THREAD

**Issue by tocsek15** [rolandtorma2/Setup_reader#11]
The goal is to have a testable json file for trying out the program.

- Create a folder in the source folder named 'resources'
- Place a sample json file, call it 'testresource.json'

**Comment by rolandtorma2** [comment]
Added a new folder to -> acc_setup_reader, added a testresource.json file to the directory

https://github.com/rolandtorma2/Setup_reader/pull/3/commits/a75430319f9af6d00d48e86cb90d2766ca1440a9

**Comment by tocsek15** [comment]
Done in this PR:
https://github.com/rolandtorma2/Setup_reader/pull/3
